package server

import "net/http"

const openAPISpec = `{
  "openapi": "3.1.0",
  "info": {
    "title": "Wirely API",
    "version": "0.9.0",
    "description": "API self-hosted para envio de mensagens pelo WhatsApp, fila persistente e painel com controle de acesso por papéis."
  },
  "servers": [{"url": "/", "description": "Servidor Wirely atual"}],
  "tags": [{"name": "Mensagens"}, {"name": "Contatos"}, {"name": "Grupos"}, {"name": "Newsletters"}, {"name": "Etiquetas"}, {"name": "Comunidades"}, {"name": "Perfil"}, {"name": "Fila"}, {"name": "Webhooks"}, {"name": "Equipe"}, {"name": "Observabilidade"}, {"name": "Autenticação"}, {"name": "Instâncias"}, {"name": "Conversas"}, {"name": "Atividade"}, {"name": "Backups"}, {"name": "Auditoria"}, {"name": "Sistema"}],
  "paths": {
    "/api/v1/health": {
      "get": {
        "tags": ["Sistema"], "summary": "Verificar a saúde do serviço", "operationId": "health",
        "responses": {"200": {"description": "Serviço disponível", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Health"}}}}}
      }
    },
    "/openapi.json": {"get": {"tags": ["Sistema"], "summary": "Obter a especificação OpenAPI", "operationId": "getOpenAPI", "responses": {"200": {"description": "Especificação OpenAPI 3.1"}}}},
    "/api/v1/openapi.json": {"get": {"tags": ["Sistema"], "summary": "Obter a especificação OpenAPI no namespace administrativo", "operationId": "getAdminOpenAPI", "responses": {"200": {"description": "Especificação OpenAPI 3.1"}}}},
    "/metrics": {"get": {"tags": ["Observabilidade"], "summary": "Expor métricas Prometheus", "operationId": "getPrometheusMetrics", "responses": {"200": {"description": "Métricas no formato Prometheus", "content": {"text/plain": {"schema": {"type": "string"}}}}}}},
    "/api/auth/login": {"post": {"tags": ["Autenticação"], "summary": "Criar sessão administrativa", "description": "Envia a senha somente nesta rota e recebe o cookie HttpOnly wirely_session.", "operationId": "loginPublicPath", "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/LoginRequest"}}}}, "responses": {"200": {"description": "Sessão criada", "headers": {"Set-Cookie": {"schema": {"type": "string"}}}, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/User"}}}}, "400": {"$ref": "#/components/responses/BadRequest"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "429": {"$ref": "#/components/responses/RateLimited"}}}},
    "/api/v1/auth/me": {"get": {"tags": ["Autenticação"], "summary": "Consultar usuário autenticado", "operationId": "getCurrentUser", "security": [{"CookieAuth": []}], "responses": {"200": {"description": "Usuário atual", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/User"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}}}},
    "/api/v1/auth/logout": {"post": {"tags": ["Autenticação"], "summary": "Encerrar sessão", "operationId": "logout", "security": [{"CookieAuth": []}], "responses": {"204": {"description": "Sessão encerrada"}, "401": {"$ref": "#/components/responses/Unauthorized"}}}},
    "/api/v1/auth/password": {"put": {"tags": ["Autenticação"], "summary": "Alterar a própria senha", "operationId": "changePassword", "security": [{"CookieAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ChangePasswordRequest"}}}}, "responses": {"204": {"description": "Senha alterada e sessões revogadas"}, "400": {"$ref": "#/components/responses/BadRequest"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/v1/alerts": {"get": {"tags": ["Observabilidade"], "summary": "Listar alertas operacionais ativos", "operationId": "listAlerts", "security": [{"CookieAuth": []}], "responses": {"200": {"description": "Alertas calculados", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/AlertList"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}}}},
    "/api/v1/audit": {"get": {"tags": ["Auditoria"], "summary": "Listar trilha de auditoria administrativa", "operationId": "listAudit", "security": [{"CookieAuth": []}], "parameters": [{"$ref": "#/components/parameters/Page"}, {"$ref": "#/components/parameters/PageSize"}, {"name": "action", "in": "query", "required": false, "schema": {"type": "string"}}], "responses": {"200": {"description": "Eventos de auditoria", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/AuditPage"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}}}},
    "/api/v1/backups": {
      "get": {"tags": ["Backups"], "summary": "Listar backups e agendamento automático", "operationId": "listBackups", "security": [{"CookieAuth": []}], "responses": {"200": {"description": "Estado dos backups", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/BackupStatus"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}}},
      "post": {"tags": ["Backups"], "summary": "Criar backup manual", "operationId": "createBackup", "security": [{"CookieAuth": []}], "responses": {"201": {"description": "Backup criado", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Backup"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}}}
    },
    "/api/v1/backups/{backupID}/download": {"get": {"tags": ["Backups"], "summary": "Baixar arquivo de backup", "operationId": "downloadBackup", "security": [{"CookieAuth": []}], "parameters": [{"$ref": "#/components/parameters/BackupID"}], "responses": {"200": {"description": "Arquivo ZIP", "content": {"application/zip": {"schema": {"type": "string", "format": "binary"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}, "404": {"$ref": "#/components/responses/NotFound"}}}},
    "/api/v1/backups/{backupID}/restore": {"post": {"tags": ["Backups"], "summary": "Preparar restauração e reinício automático", "operationId": "restoreBackup", "security": [{"CookieAuth": []}], "parameters": [{"$ref": "#/components/parameters/BackupID"}], "responses": {"202": {"description": "Restauração preparada"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}, "404": {"$ref": "#/components/responses/NotFound"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/v1/backups/{backupID}": {"delete": {"tags": ["Backups"], "summary": "Excluir backup", "operationId": "deleteBackup", "security": [{"CookieAuth": []}], "parameters": [{"$ref": "#/components/parameters/BackupID"}], "responses": {"204": {"description": "Backup excluído"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}, "404": {"$ref": "#/components/responses/NotFound"}}}},
    "/api/v1/metrics": {
      "get": {
        "tags": ["Observabilidade"], "summary": "Consultar métricas operacionais", "operationId": "getMetrics", "security": [{"CookieAuth": []}],
        "parameters": [{"name": "range", "in": "query", "required": false, "schema": {"type": "string", "enum": ["24h", "7d", "30d"], "default": "24h"}}],
        "responses": {"200": {"description": "Resumo operacional consolidado e por instância", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/MetricsSnapshot"}}}}, "400": {"$ref": "#/components/responses/BadRequest"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}}
      }
    },
    "/api/send/text": {
      "post": {
        "tags": ["Mensagens"], "summary": "Enviar mensagem de texto", "operationId": "sendText", "security": [{"BearerAuth": []}],
        "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/TextRequest"}}}},
        "responses": {"201": {"$ref": "#/components/responses/Sent"}, "400": {"$ref": "#/components/responses/BadRequest"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}
      }
    },
    "/api/send/media": {"post": {"tags": ["Mensagens"], "summary": "Enviar imagem, vídeo, áudio, documento ou figurinha", "operationId": "sendMedia", "security": [{"BearerAuth": []}], "requestBody": {"$ref": "#/components/requestBodies/Media"}, "responses": {"201": {"$ref": "#/components/responses/Sent"}, "400": {"$ref": "#/components/responses/BadRequest"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "413": {"$ref": "#/components/responses/TooLarge"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/send/location": {"post": {"tags": ["Mensagens"], "summary": "Enviar localização", "operationId": "sendLocation", "security": [{"BearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/LocationRequest"}}}}, "responses": {"201": {"$ref": "#/components/responses/Sent"}, "400": {"$ref": "#/components/responses/BadRequest"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/send/contact": {"post": {"tags": ["Mensagens"], "summary": "Enviar contato", "operationId": "sendContact", "security": [{"BearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ContactRequest"}}}}, "responses": {"201": {"$ref": "#/components/responses/Sent"}, "400": {"$ref": "#/components/responses/BadRequest"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/send/poll": {"post": {"tags": ["Mensagens"], "summary": "Enviar enquete", "operationId": "sendPoll", "security": [{"BearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/PollRequest"}}}}, "responses": {"201": {"$ref": "#/components/responses/Sent"}, "400": {"$ref": "#/components/responses/BadRequest"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/send/reaction": {"post": {"tags": ["Mensagens"], "summary": "Reagir a uma mensagem ou remover reação", "operationId": "sendReaction", "security": [{"BearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ReactionRequest"}}}}, "responses": {"201": {"$ref": "#/components/responses/Sent"}, "400": {"$ref": "#/components/responses/BadRequest"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/messages/{messageID}/media": {"get": {"tags": ["Mensagens"], "summary": "Baixar mídia recebida", "description": "Retorna o arquivo descriptografado armazenado pelo Wirely ou um objeto JSON com o conteúdo em Base64.", "operationId": "downloadReceivedMedia", "security": [{"BearerAuth": []}], "parameters": [{"$ref": "#/components/parameters/MessageID"}, {"name": "format", "in": "query", "required": false, "schema": {"type": "string", "enum": ["file", "base64"], "default": "file"}}], "responses": {"200": {"description": "Mídia recebida", "content": {"application/octet-stream": {"schema": {"type": "string", "format": "binary"}}, "application/json": {"schema": {"$ref": "#/components/schemas/ReceivedMediaBase64"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "404": {"$ref": "#/components/responses/NotFound"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/messages/delete": {"post": {"tags": ["Mensagens"], "summary": "Excluir mensagem para todos", "operationId": "deleteMessage", "security": [{"BearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/DeleteMessageRequest"}}}}, "responses": {"200": {"description": "Mensagem excluída", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/MessageActionResult"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/messages/edit": {"post": {"tags": ["Mensagens"], "summary": "Editar mensagem de texto", "operationId": "editMessage", "security": [{"BearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/EditMessageRequest"}}}}, "responses": {"200": {"description": "Mensagem editada", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/MessageActionResult"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/messages/read": {"post": {"tags": ["Mensagens"], "summary": "Marcar mensagens como lidas", "operationId": "markMessagesRead", "security": [{"BearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/MarkMessagesReadRequest"}}}}, "responses": {"200": {"description": "Confirmação enviada", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/MessageActionResult"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/messages/{messageID}/status": {"get": {"tags": ["Mensagens"], "summary": "Consultar status da mensagem", "operationId": "getMessageStatus", "security": [{"BearerAuth": []}], "parameters": [{"$ref": "#/components/parameters/MessageID"}], "responses": {"200": {"description": "Último recibo persistido", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/MessageStatus"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "404": {"$ref": "#/components/responses/NotFound"}}}},
    "/api/chats/archive": {"post": {"tags": ["Conversas"], "summary": "Arquivar ou desarquivar conversa", "operationId": "archiveChat", "security": [{"BearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ArchiveChatRequest"}}}}, "responses": {"200": {"description": "Conversa atualizada", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ChatActionResult"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/chats/mute": {"post": {"tags": ["Conversas"], "summary": "Silenciar conversa", "operationId": "muteChat", "security": [{"BearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/MuteChatRequest"}}}}, "responses": {"200": {"description": "Conversa silenciada", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ChatActionResult"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/chats/pin": {"post": {"tags": ["Conversas"], "summary": "Fixar conversa", "operationId": "pinChat", "security": [{"BearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ChatActionRequest"}}}}, "responses": {"200": {"description": "Conversa fixada", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ChatActionResult"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/chats/unpin": {"post": {"tags": ["Conversas"], "summary": "Desafixar conversa", "operationId": "unpinChat", "security": [{"BearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ChatActionRequest"}}}}, "responses": {"200": {"description": "Conversa desafixada", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ChatActionResult"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/newsletters": {
      "get": {"tags": ["Newsletters"], "summary": "Listar newsletters assinadas", "operationId": "listNewsletters", "security": [{"BearerAuth": []}], "responses": {"200": {"description": "Lista de newsletters"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}},
      "post": {"tags": ["Newsletters"], "summary": "Criar newsletter", "operationId": "createNewsletter", "security": [{"BearerAuth": []}], "requestBody": {"$ref": "#/components/requestBodies/NewsletterCreate"}, "responses": {"201": {"description": "Newsletter criada", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Newsletter"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}
    },
    "/api/newsletters/info": {"post": {"tags": ["Newsletters"], "summary": "Consultar newsletter", "operationId": "getNewsletter", "security": [{"BearerAuth": []}], "requestBody": {"$ref": "#/components/requestBodies/NewsletterJID"}, "responses": {"200": {"description": "Newsletter", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Newsletter"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/newsletters/invite": {"post": {"tags": ["Newsletters"], "summary": "Consultar newsletter por convite", "operationId": "getNewsletterByInvite", "security": [{"BearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/NewsletterInviteRequest"}}}}, "responses": {"200": {"description": "Newsletter", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Newsletter"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/newsletters/messages": {"post": {"tags": ["Newsletters"], "summary": "Obter mensagens da newsletter", "operationId": "getNewsletterMessages", "security": [{"BearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/NewsletterMessagesRequest"}}}}, "responses": {"200": {"description": "Mensagens"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/newsletters/subscribe": {"post": {"tags": ["Newsletters"], "summary": "Assinar newsletter", "operationId": "subscribeNewsletter", "security": [{"BearerAuth": []}], "requestBody": {"$ref": "#/components/requestBodies/NewsletterJID"}, "responses": {"200": {"description": "Assinatura concluída"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/labels/chat": {
      "post": {"tags": ["Etiquetas"], "summary": "Adicionar etiqueta à conversa", "operationId": "addChatLabel", "security": [{"BearerAuth": []}], "requestBody": {"$ref": "#/components/requestBodies/ChatLabel"}, "responses": {"200": {"description": "Etiqueta associada"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}},
      "delete": {"tags": ["Etiquetas"], "summary": "Remover etiqueta da conversa", "operationId": "removeChatLabel", "security": [{"BearerAuth": []}], "requestBody": {"$ref": "#/components/requestBodies/ChatLabel"}, "responses": {"200": {"description": "Associação removida"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}
    },
    "/api/labels/message": {
      "post": {"tags": ["Etiquetas"], "summary": "Adicionar etiqueta à mensagem", "operationId": "addMessageLabel", "security": [{"BearerAuth": []}], "requestBody": {"$ref": "#/components/requestBodies/MessageLabel"}, "responses": {"200": {"description": "Etiqueta associada"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}},
      "delete": {"tags": ["Etiquetas"], "summary": "Remover etiqueta da mensagem", "operationId": "removeMessageLabel", "security": [{"BearerAuth": []}], "requestBody": {"$ref": "#/components/requestBodies/MessageLabel"}, "responses": {"200": {"description": "Associação removida"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}
    },
    "/api/labels/{labelID}": {"patch": {"tags": ["Etiquetas"], "summary": "Editar ou excluir etiqueta", "operationId": "editLabel", "security": [{"BearerAuth": []}], "parameters": [{"name": "labelID", "in": "path", "required": true, "schema": {"type": "string"}}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/LabelEditRequest"}}}}, "responses": {"200": {"description": "Etiqueta atualizada"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/communities": {"post": {"tags": ["Comunidades"], "summary": "Criar comunidade", "operationId": "createCommunity", "security": [{"BearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/CommunityCreateRequest"}}}}, "responses": {"201": {"description": "Comunidade criada", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Group"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/communities/groups": {
      "post": {"tags": ["Comunidades"], "summary": "Vincular grupos à comunidade", "operationId": "addCommunityGroups", "security": [{"BearerAuth": []}], "requestBody": {"$ref": "#/components/requestBodies/CommunityGroups"}, "responses": {"200": {"description": "Resultado por grupo"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}},
      "delete": {"tags": ["Comunidades"], "summary": "Desvincular grupos da comunidade", "operationId": "removeCommunityGroups", "security": [{"BearerAuth": []}], "requestBody": {"$ref": "#/components/requestBodies/CommunityGroups"}, "responses": {"200": {"description": "Resultado por grupo"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}
    },
    "/api/instance": {"get": {"tags": ["Instâncias"], "summary": "Consultar a instância do token", "operationId": "getOwnInstance", "security": [{"BearerAuth": []}], "responses": {"200": {"description": "Instância autenticada", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Instance"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}}}},
    "/api/instance/connect": {"post": {"tags": ["Instâncias"], "summary": "Conectar a instância", "operationId": "connectOwnInstance", "security": [{"BearerAuth": []}], "responses": {"202": {"description": "Conexão iniciada"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/instance/disconnect": {"post": {"tags": ["Instâncias"], "summary": "Desconectar sem remover o pareamento", "operationId": "disconnectOwnInstance", "security": [{"BearerAuth": []}], "responses": {"204": {"description": "Instância desconectada"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/instance/logout": {"delete": {"tags": ["Instâncias"], "summary": "Encerrar sessão e remover o pareamento", "operationId": "logoutOwnInstance", "security": [{"BearerAuth": []}], "responses": {"204": {"description": "Logout concluído"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/instance/pair": {"post": {"tags": ["Instâncias"], "summary": "Solicitar código de pareamento", "description": "O telefone deve estar no formato internacional sem o caractere +.", "operationId": "pairOwnInstance", "security": [{"BearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/PairInstanceRequest"}}}}, "responses": {"200": {"description": "Código temporário", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/PairInstanceResponse"}}}}, "400": {"$ref": "#/components/responses/BadRequest"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/Conflict"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/instance/proxy": {"delete": {"tags": ["Instâncias"], "summary": "Remover proxy em uso", "description": "Limpa o proxy do cliente e reconecta quando necessário.", "operationId": "deleteOwnInstanceProxy", "security": [{"BearerAuth": []}], "responses": {"204": {"description": "Proxy removido"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/instance/qr": {"get": {"tags": ["Instâncias"], "summary": "Obter QR Code da instância", "operationId": "getOwnInstanceQR", "security": [{"BearerAuth": []}], "parameters": [{"name": "format", "in": "query", "schema": {"type": "string", "enum": ["file", "base64"], "default": "file"}}], "responses": {"200": {"description": "QR Code", "content": {"image/png": {"schema": {"type": "string", "format": "binary"}}, "application/json": {"schema": {"$ref": "#/components/schemas/QRCodeBase64"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "404": {"$ref": "#/components/responses/NotFound"}}}},
    "/api/instance/status": {"get": {"tags": ["Instâncias"], "summary": "Consultar status da instância", "operationId": "getOwnInstanceStatus", "security": [{"BearerAuth": []}], "responses": {"200": {"description": "Estado atual", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ConnectionState"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "404": {"$ref": "#/components/responses/NotFound"}}}},
    "/api/contacts/check": {"post": {"tags": ["Contatos"], "summary": "Verificar números no WhatsApp", "description": "Aceita até 100 telefones internacionais sem +.", "operationId": "checkContacts", "security": [{"BearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ContactCheckRequest"}}}}, "responses": {"200": {"description": "Resultado por telefone", "content": {"application/json": {"schema": {"type": "object", "required": ["data"], "properties": {"data": {"type": "array", "items": {"$ref": "#/components/schemas/ContactCheck"}}}}}}}, "400": {"$ref": "#/components/responses/BadRequest"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/groups": {
      "get": {"tags": ["Grupos"], "summary": "Listar grupos da instância", "operationId": "listGroups", "security": [{"BearerAuth": []}], "responses": {"200": {"description": "Grupos participantes", "content": {"application/json": {"schema": {"type": "object", "required": ["data"], "properties": {"data": {"type": "array", "items": {"$ref": "#/components/schemas/Group"}}}}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}}},
      "post": {"tags": ["Grupos"], "summary": "Criar grupo", "operationId": "createGroup", "security": [{"BearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/CreateGroupRequest"}}}}, "responses": {"201": {"description": "Grupo criado", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Group"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}
    },
    "/api/groups/join": {"post": {"tags": ["Grupos"], "summary": "Entrar em grupo por convite", "operationId": "joinGroup", "security": [{"BearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/JoinGroupRequest"}}}}, "responses": {"200": {"description": "Grupo ingressado", "content": {"application/json": {"schema": {"type": "object", "required": ["jid"], "properties": {"jid": {"type": "string"}}}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/groups/{groupJID}": {
      "parameters": [{"$ref": "#/components/parameters/GroupJID"}],
      "get": {"tags": ["Grupos"], "summary": "Consultar grupo e participantes", "operationId": "getGroup", "security": [{"BearerAuth": []}], "responses": {"200": {"description": "Dados do grupo", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Group"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}},
      "patch": {"tags": ["Grupos"], "summary": "Alterar nome do grupo", "operationId": "setGroupName", "security": [{"BearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/UpdateGroupNameRequest"}}}}, "responses": {"204": {"description": "Nome alterado"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}
    },
    "/api/groups/{groupJID}/participants": {"post": {"tags": ["Grupos"], "summary": "Adicionar, remover, promover ou rebaixar participantes", "operationId": "updateGroupParticipants", "security": [{"BearerAuth": []}], "parameters": [{"$ref": "#/components/parameters/GroupJID"}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/UpdateGroupParticipantsRequest"}}}}, "responses": {"200": {"description": "Resultado por participante", "content": {"application/json": {"schema": {"type": "object", "required": ["data"], "properties": {"data": {"type": "array", "items": {"$ref": "#/components/schemas/GroupParticipant"}}}}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/groups/{groupJID}/invite": {
      "parameters": [{"$ref": "#/components/parameters/GroupJID"}],
      "get": {"tags": ["Grupos"], "summary": "Obter link de convite", "operationId": "getGroupInvite", "security": [{"BearerAuth": []}], "responses": {"200": {"description": "Link atual", "content": {"application/json": {"schema": {"type": "object", "required": ["link"], "properties": {"link": {"type": "string", "format": "uri"}}}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}},
      "post": {"tags": ["Grupos"], "summary": "Revogar e gerar novo link de convite", "operationId": "rotateGroupInvite", "security": [{"BearerAuth": []}], "responses": {"200": {"description": "Novo link", "content": {"application/json": {"schema": {"type": "object", "required": ["link"], "properties": {"link": {"type": "string", "format": "uri"}}}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}
    },
    "/api/profile": {
      "get": {"tags": ["Perfil"], "summary": "Consultar perfil da instância", "operationId": "getProfile", "security": [{"BearerAuth": []}], "responses": {"200": {"description": "Perfil atual", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Profile"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}},
      "patch": {"tags": ["Perfil"], "summary": "Alterar nome e/ou recado", "operationId": "updateProfile", "security": [{"BearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/UpdateProfileRequest"}}}}, "responses": {"204": {"description": "Perfil alterado"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}
    },
    "/api/profile/photo": {
      "put": {"tags": ["Perfil"], "summary": "Definir foto JPEG do perfil", "operationId": "setProfilePhoto", "security": [{"BearerAuth": []}], "requestBody": {"$ref": "#/components/requestBodies/ProfilePhoto"}, "responses": {"200": {"description": "Foto atualizada", "content": {"application/json": {"schema": {"type": "object", "required": ["pictureId"], "properties": {"pictureId": {"type": "string"}}}}}}, "400": {"$ref": "#/components/responses/BadRequest"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "413": {"$ref": "#/components/responses/TooLarge"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}},
      "delete": {"tags": ["Perfil"], "summary": "Remover foto do perfil", "operationId": "deleteProfilePhoto", "security": [{"BearerAuth": []}], "responses": {"204": {"description": "Foto removida"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}
    },
    "/api/profile/privacy": {
      "get": {"tags": ["Perfil"], "summary": "Consultar privacidade", "operationId": "getPrivacySettings", "security": [{"BearerAuth": []}], "responses": {"200": {"description": "Configurações atuais", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/PrivacySettings"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}},
      "patch": {"tags": ["Perfil"], "summary": "Alterar uma configuração de privacidade", "operationId": "setPrivacySetting", "security": [{"BearerAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/UpdatePrivacyRequest"}}}}, "responses": {"200": {"description": "Configurações atualizadas", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/PrivacySettings"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}
    },
    "/api/v1/instances": {
      "get": {"tags": ["Instâncias"], "summary": "Listar instâncias", "operationId": "listInstances", "security": [{"CookieAuth": []}], "responses": {"200": {"description": "Instâncias cadastradas", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/InstanceList"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}}},
      "post": {"tags": ["Instâncias"], "summary": "Criar instância", "operationId": "createInstance", "security": [{"CookieAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/CreateInstanceRequest"}}}}, "responses": {"201": {"description": "Instância criada", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Instance"}}}}, "400": {"$ref": "#/components/responses/BadRequest"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}
    },
    "/api/v1/instances/{id}": {"delete": {"tags": ["Instâncias"], "summary": "Excluir instância e dados relacionados", "operationId": "deleteInstance", "security": [{"CookieAuth": []}], "parameters": [{"$ref": "#/components/parameters/InstanceID"}], "responses": {"204": {"description": "Instância excluída"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}, "404": {"$ref": "#/components/responses/NotFound"}}}},
    "/api/v1/instances/{id}/connect": {"post": {"tags": ["Instâncias"], "summary": "Iniciar conexão ou pareamento", "operationId": "connectInstance", "security": [{"CookieAuth": []}], "parameters": [{"$ref": "#/components/parameters/InstanceID"}], "responses": {"202": {"description": "Conexão iniciada"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/v1/instances/{id}/disconnect": {"post": {"tags": ["Instâncias"], "summary": "Desconectar instância", "operationId": "disconnectInstance", "security": [{"CookieAuth": []}], "parameters": [{"$ref": "#/components/parameters/InstanceID"}], "responses": {"204": {"description": "Instância desconectada"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/v1/instances/{id}/state": {"get": {"tags": ["Instâncias"], "summary": "Consultar estado da conexão", "operationId": "getInstanceState", "security": [{"CookieAuth": []}], "parameters": [{"$ref": "#/components/parameters/InstanceID"}], "responses": {"200": {"description": "Estado atual", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ConnectionState"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}, "404": {"$ref": "#/components/responses/NotFound"}}}},
    "/api/v1/instances/{id}/qr": {"get": {"tags": ["Instâncias"], "summary": "Obter QR Code de pareamento", "operationId": "getInstanceQR", "security": [{"CookieAuth": []}], "parameters": [{"$ref": "#/components/parameters/InstanceID"}], "responses": {"200": {"description": "QR Code PNG", "content": {"image/png": {"schema": {"type": "string", "format": "binary"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}, "404": {"$ref": "#/components/responses/NotFound"}}}},
    "/api/v1/instances/{id}/token": {
      "get": {"tags": ["Instâncias"], "summary": "Consultar token da instância", "operationId": "getInstanceToken", "security": [{"CookieAuth": []}], "parameters": [{"$ref": "#/components/parameters/InstanceID"}], "responses": {"200": {"description": "Token atual", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/TokenResponse"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}, "404": {"$ref": "#/components/responses/NotFound"}}},
      "post": {"tags": ["Instâncias"], "summary": "Gerar ou renovar token", "operationId": "rotateInstanceToken", "security": [{"CookieAuth": []}], "parameters": [{"$ref": "#/components/parameters/InstanceID"}], "responses": {"201": {"description": "Novo token", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/TokenResponse"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}
    },
    "/api/v1/instances/{id}/webhook": {
      "get": {"tags": ["Instâncias"], "summary": "Consultar webhook único", "operationId": "getInstanceWebhook", "security": [{"CookieAuth": []}], "parameters": [{"$ref": "#/components/parameters/InstanceID"}], "responses": {"200": {"description": "Configuração atual", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/WebhookConfig"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}, "404": {"$ref": "#/components/responses/NotFound"}}},
      "put": {"tags": ["Instâncias"], "summary": "Atualizar webhook único", "operationId": "updateInstanceWebhook", "security": [{"CookieAuth": []}], "parameters": [{"$ref": "#/components/parameters/InstanceID"}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/WebhookRequest"}}}}, "responses": {"200": {"description": "Configuração salva", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/WebhookConfig"}}}}, "400": {"$ref": "#/components/responses/BadRequest"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}, "404": {"$ref": "#/components/responses/NotFound"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}
    },
    "/api/v1/instances/{id}/events": {"get": {"tags": ["Atividade"], "summary": "Listar eventos", "operationId": "listActivityEvents", "security": [{"CookieAuth": []}], "parameters": [{"$ref": "#/components/parameters/InstanceID"}, {"$ref": "#/components/parameters/Page"}, {"$ref": "#/components/parameters/PageSize"}, {"name": "category", "in": "query", "schema": {"type": "string", "default": "all"}}], "responses": {"200": {"description": "Eventos paginados", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ActivityPage"}}}}, "400": {"$ref": "#/components/responses/BadRequest"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}}}},
    "/api/v1/instances/{id}/webhook-deliveries": {"get": {"tags": ["Atividade"], "summary": "Listar entregas de webhook", "operationId": "listWebhookDeliveries", "security": [{"CookieAuth": []}], "parameters": [{"$ref": "#/components/parameters/InstanceID"}, {"$ref": "#/components/parameters/Page"}, {"$ref": "#/components/parameters/PageSize"}, {"name": "status", "in": "query", "schema": {"type": "string", "enum": ["all", "delivered", "failed"]}}], "responses": {"200": {"description": "Entregas paginadas", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/WebhookDeliveryPage"}}}}, "400": {"$ref": "#/components/responses/BadRequest"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}}}},
    "/api/v1/instances/{id}/webhook-deliveries/{deliveryID}/retry": {"post": {"tags": ["Atividade"], "summary": "Reenfileirar webhook com falha", "operationId": "retryWebhookDelivery", "security": [{"CookieAuth": []}], "parameters": [{"$ref": "#/components/parameters/InstanceID"}, {"$ref": "#/components/parameters/DeliveryID"}], "responses": {"202": {"description": "Webhook reenfileirado"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}, "404": {"$ref": "#/components/responses/NotFound"}, "409": {"$ref": "#/components/responses/Conflict"}}}},
    "/api/v1/instances/{id}/contacts": {"get": {"tags": ["Conversas"], "summary": "Listar contatos sincronizados", "operationId": "listContacts", "security": [{"CookieAuth": []}], "parameters": [{"$ref": "#/components/parameters/InstanceID"}, {"$ref": "#/components/parameters/Page"}, {"$ref": "#/components/parameters/PageSize"}, {"name": "search", "in": "query", "schema": {"type": "string", "maxLength": 100}}], "responses": {"200": {"description": "Contatos paginados", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ContactPage"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}}}},
    "/api/v1/instances/{id}/chats": {"get": {"tags": ["Conversas"], "summary": "Listar conversas", "operationId": "listChats", "security": [{"CookieAuth": []}], "parameters": [{"$ref": "#/components/parameters/InstanceID"}, {"$ref": "#/components/parameters/Page"}, {"$ref": "#/components/parameters/PageSize"}, {"name": "search", "in": "query", "schema": {"type": "string", "maxLength": 100}}], "responses": {"200": {"description": "Conversas paginadas", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ChatPage"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}}}},
    "/api/v1/instances/{id}/chats/{chat}/messages": {
      "get": {"tags": ["Conversas"], "summary": "Listar mensagens", "operationId": "listChatMessages", "security": [{"CookieAuth": []}], "parameters": [{"$ref": "#/components/parameters/InstanceID"}, {"$ref": "#/components/parameters/Chat"}, {"$ref": "#/components/parameters/Page"}, {"$ref": "#/components/parameters/PageSize"}], "responses": {"200": {"description": "Mensagens paginadas", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ChatMessagePage"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}}},
      "post": {"tags": ["Conversas"], "summary": "Enviar texto pela conversa", "operationId": "sendChatMessage", "security": [{"CookieAuth": []}], "parameters": [{"$ref": "#/components/parameters/InstanceID"}, {"$ref": "#/components/parameters/Chat"}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ChatTextRequest"}}}}, "responses": {"201": {"$ref": "#/components/responses/Sent"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}, "409": {"$ref": "#/components/responses/NotConnected"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}
    },
    "/api/v1/instances/{id}/chats/{chat}/read": {"post": {"tags": ["Conversas"], "summary": "Marcar conversa como lida", "operationId": "markChatRead", "security": [{"CookieAuth": []}], "parameters": [{"$ref": "#/components/parameters/InstanceID"}, {"$ref": "#/components/parameters/Chat"}], "responses": {"204": {"description": "Conversa marcada como lida"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}}}},
    "/api/v1/instances/{id}/queue": {"get": {"tags": ["Fila"], "summary": "Listar fila da instância no painel", "operationId": "listInstanceQueue", "security": [{"CookieAuth": []}], "parameters": [{"$ref": "#/components/parameters/InstanceID"}, {"$ref": "#/components/parameters/Page"}, {"$ref": "#/components/parameters/PageSize"}, {"name": "status", "in": "query", "schema": {"type": "string"}}], "responses": {"200": {"description": "Jobs paginados", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/MessageJobPage"}}}}, "400": {"$ref": "#/components/responses/BadRequest"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}}}},
    "/api/v1/instances/{id}/queue/{jobID}": {"delete": {"tags": ["Fila"], "summary": "Cancelar job pelo painel", "operationId": "cancelInstanceQueueJob", "security": [{"CookieAuth": []}], "parameters": [{"$ref": "#/components/parameters/InstanceID"}, {"$ref": "#/components/parameters/JobID"}], "responses": {"200": {"$ref": "#/components/responses/Queued"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}, "404": {"$ref": "#/components/responses/NotFound"}, "409": {"$ref": "#/components/responses/Conflict"}}}},
    "/api/v1/instances/{id}/queue/{jobID}/retry": {"post": {"tags": ["Fila"], "summary": "Reenfileirar job pelo painel", "operationId": "retryInstanceQueueJob", "security": [{"CookieAuth": []}], "parameters": [{"$ref": "#/components/parameters/InstanceID"}, {"$ref": "#/components/parameters/JobID"}], "responses": {"202": {"$ref": "#/components/responses/Queued"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}, "404": {"$ref": "#/components/responses/NotFound"}, "409": {"$ref": "#/components/responses/Conflict"}}}},
    "/api/v1/users": {
      "get": {"tags": ["Equipe"], "summary": "Listar usuários do painel", "operationId": "listUsers", "security": [{"CookieAuth": []}], "responses": {"200": {"description": "Equipe cadastrada", "content": {"application/json": {"schema": {"type": "object", "required": ["data"], "properties": {"data": {"type": "array", "items": {"$ref": "#/components/schemas/User"}}}}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}}},
      "post": {"tags": ["Equipe"], "summary": "Criar usuário", "operationId": "createUser", "security": [{"CookieAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/CreateUserRequest"}}}}, "responses": {"201": {"description": "Usuário criado", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/User"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}, "409": {"$ref": "#/components/responses/Conflict"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}
    },
    "/api/v1/users/{userID}": {
      "parameters": [{"name": "userID", "in": "path", "required": true, "schema": {"type": "string", "pattern": "^usr_"}}],
      "patch": {"tags": ["Equipe"], "summary": "Alterar papel ou acesso", "operationId": "updateUser", "security": [{"CookieAuth": []}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/UpdateUserRequest"}}}}, "responses": {"200": {"description": "Usuário atualizado", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/User"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}, "404": {"$ref": "#/components/responses/NotFound"}, "409": {"$ref": "#/components/responses/Conflict"}}},
      "delete": {"tags": ["Equipe"], "summary": "Excluir usuário", "operationId": "deleteUser", "security": [{"CookieAuth": []}], "responses": {"204": {"description": "Usuário removido"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}, "404": {"$ref": "#/components/responses/NotFound"}, "409": {"$ref": "#/components/responses/Conflict"}}}
    },
    "/api/v1/users/{userID}/password": {"put": {"tags": ["Equipe"], "summary": "Redefinir senha de usuário", "operationId": "resetUserPassword", "security": [{"CookieAuth": []}], "parameters": [{"name": "userID", "in": "path", "required": true, "schema": {"type": "string", "pattern": "^usr_"}}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ResetUserPasswordRequest"}}}}, "responses": {"204": {"description": "Senha redefinida e sessões revogadas"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "403": {"$ref": "#/components/responses/Forbidden"}, "404": {"$ref": "#/components/responses/NotFound"}, "409": {"$ref": "#/components/responses/Conflict"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/webhook/test": {"post": {"tags": ["Webhooks"], "summary": "Enviar evento de teste ao webhook", "description": "Cria um evento webhook.test na fila persistente da instância.", "operationId": "testWebhook", "security": [{"BearerAuth": []}], "responses": {"202": {"description": "Teste enfileirado", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/WebhookAccepted"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/Conflict"}}}},
    "/api/webhook/jobs/{eventID}": {"get": {"tags": ["Webhooks"], "summary": "Consultar estado de um webhook", "operationId": "getWebhookJob", "security": [{"BearerAuth": []}], "parameters": [{"$ref": "#/components/parameters/EventID"}], "responses": {"200": {"description": "Estado da entrega", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/WebhookJob"}}}}, "401": {"$ref": "#/components/responses/Unauthorized"}, "404": {"$ref": "#/components/responses/NotFound"}}}},
    "/api/webhook/deliveries": {"get": {"tags": ["Webhooks"], "summary": "Listar tentativas de webhook", "operationId": "listPublicWebhookDeliveries", "security": [{"BearerAuth": []}], "parameters": [{"$ref": "#/components/parameters/Page"}, {"$ref": "#/components/parameters/PageSize"}, {"name": "status", "in": "query", "schema": {"type": "string", "enum": ["all", "delivered", "failed"], "default": "all"}}], "responses": {"200": {"description": "Tentativas paginadas", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/WebhookDeliveryPage"}}}}, "400": {"$ref": "#/components/responses/BadRequest"}, "401": {"$ref": "#/components/responses/Unauthorized"}}}},
    "/api/queue/text": {"post": {"tags": ["Fila"], "summary": "Enfileirar texto", "operationId": "queueText", "security": [{"BearerAuth": []}], "parameters": [{"$ref": "#/components/parameters/IdempotencyKey"}], "requestBody": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/QueueTextRequest"}}}}, "responses": {"200": {"$ref": "#/components/responses/Queued"}, "202": {"$ref": "#/components/responses/Queued"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/Conflict"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/queue/media": {"post": {"tags": ["Fila"], "summary": "Enfileirar imagem, vídeo, áudio, documento ou figurinha", "operationId": "queueMedia", "security": [{"BearerAuth": []}], "parameters": [{"$ref": "#/components/parameters/IdempotencyKey"}], "requestBody": {"$ref": "#/components/requestBodies/QueueMedia"}, "responses": {"200": {"$ref": "#/components/responses/Queued"}, "202": {"$ref": "#/components/responses/Queued"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "409": {"$ref": "#/components/responses/Conflict"}, "413": {"$ref": "#/components/responses/TooLarge"}, "422": {"$ref": "#/components/responses/InvalidPayload"}}}},
    "/api/queue/{jobID}": {
      "parameters": [{"name": "jobID", "in": "path", "required": true, "schema": {"type": "string", "pattern": "^job_"}}],
      "get": {"tags": ["Fila"], "summary": "Consultar um envio", "operationId": "getQueuedMessage", "security": [{"BearerAuth": []}], "responses": {"200": {"$ref": "#/components/responses/Queued"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "404": {"$ref": "#/components/responses/NotFound"}}},
      "delete": {"tags": ["Fila"], "summary": "Cancelar um envio pendente", "operationId": "cancelQueuedMessage", "security": [{"BearerAuth": []}], "responses": {"200": {"$ref": "#/components/responses/Queued"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "404": {"$ref": "#/components/responses/NotFound"}, "409": {"$ref": "#/components/responses/Conflict"}}}
    },
    "/api/queue/{jobID}/retry": {"post": {"tags": ["Fila"], "summary": "Reenfileirar um envio que falhou", "operationId": "retryQueuedMessage", "security": [{"BearerAuth": []}], "parameters": [{"name": "jobID", "in": "path", "required": true, "schema": {"type": "string", "pattern": "^job_"}}], "responses": {"202": {"$ref": "#/components/responses/Queued"}, "401": {"$ref": "#/components/responses/Unauthorized"}, "404": {"$ref": "#/components/responses/NotFound"}, "409": {"$ref": "#/components/responses/Conflict"}}}}
  },
  "components": {
    "securitySchemes": {"BearerAuth": {"type": "http", "scheme": "bearer", "bearerFormat": "Wirely instance token"}, "CookieAuth": {"type": "apiKey", "in": "cookie", "name": "wirely_session", "description": "Sessão HttpOnly do painel. Métricas exigem viewer ou superior; equipe exige owner."}},
    "parameters": {
      "GroupJID": {"name": "groupJID", "in": "path", "required": true, "description": "JID do grupo", "schema": {"type": "string", "pattern": "^[^@]+@g\\.us$"}},
      "IdempotencyKey": {"name": "Idempotency-Key", "in": "header", "required": false, "schema": {"type": "string", "maxLength": 128}},
      "InstanceID": {"name": "id", "in": "path", "required": true, "schema": {"type": "string"}},
      "BackupID": {"name": "backupID", "in": "path", "required": true, "schema": {"type": "string", "pattern": "^wirely-[A-Za-z0-9_-]+$"}},
      "DeliveryID": {"name": "deliveryID", "in": "path", "required": true, "schema": {"type": "integer", "minimum": 1}},
      "EventID": {"name": "eventID", "in": "path", "required": true, "description": "Identificador idempotente enviado em X-Wirely-Delivery", "schema": {"type": "string", "minLength": 1}},
      "MessageID": {"name": "messageID", "in": "path", "required": true, "description": "ID informado no evento message.received", "schema": {"type": "string", "minLength": 1}},
      "JobID": {"name": "jobID", "in": "path", "required": true, "schema": {"type": "string", "pattern": "^job_"}},
      "Chat": {"name": "chat", "in": "path", "required": true, "description": "JID da conversa codificado para URL", "schema": {"type": "string"}},
      "Page": {"name": "page", "in": "query", "required": false, "schema": {"type": "integer", "minimum": 1, "default": 1}},
      "PageSize": {"name": "pageSize", "in": "query", "required": false, "schema": {"type": "integer", "minimum": 1, "maximum": 100, "default": 25}}
    },
    "schemas": {
      "MetricMessages": {"type": "object", "required": ["sent", "received", "total"], "properties": {"sent": {"type": "integer"}, "received": {"type": "integer"}, "total": {"type": "integer"}}},
      "MetricQueue": {"type": "object", "required": ["queued", "processing", "retrying", "pending", "sent", "failed", "canceled"], "properties": {"queued": {"type": "integer"}, "processing": {"type": "integer"}, "retrying": {"type": "integer"}, "pending": {"type": "integer"}, "sent": {"type": "integer"}, "failed": {"type": "integer"}, "canceled": {"type": "integer"}}},
      "MetricWebhooks": {"type": "object", "required": ["delivered", "failed", "total", "successRate", "averageTimeMs"], "properties": {"delivered": {"type": "integer"}, "failed": {"type": "integer"}, "total": {"type": "integer"}, "successRate": {"type": "number", "minimum": 0, "maximum": 100}, "averageTimeMs": {"type": "number", "minimum": 0}}},
      "InstanceMetric": {"type": "object", "required": ["id", "name", "status", "messages", "queue", "webhooks"], "properties": {"id": {"type": "string"}, "name": {"type": "string"}, "status": {"type": "string"}, "messages": {"$ref": "#/components/schemas/MetricMessages"}, "queue": {"$ref": "#/components/schemas/MetricQueue"}, "webhooks": {"$ref": "#/components/schemas/MetricWebhooks"}}},
      "MetricsSnapshot": {"type": "object", "required": ["range", "from", "to", "generatedAt", "uptimeSeconds", "instances", "messages", "queue", "webhooks", "byInstance"], "properties": {"range": {"type": "string", "enum": ["24h", "7d", "30d"]}, "from": {"type": "string", "format": "date-time"}, "to": {"type": "string", "format": "date-time"}, "generatedAt": {"type": "string", "format": "date-time"}, "uptimeSeconds": {"type": "integer", "minimum": 0}, "instances": {"type": "object", "required": ["total", "connected"], "properties": {"total": {"type": "integer"}, "connected": {"type": "integer"}}}, "messages": {"$ref": "#/components/schemas/MetricMessages"}, "queue": {"$ref": "#/components/schemas/MetricQueue"}, "webhooks": {"$ref": "#/components/schemas/MetricWebhooks"}, "byInstance": {"type": "array", "items": {"$ref": "#/components/schemas/InstanceMetric"}}}},
      "Health": {"type": "object", "required": ["service", "status", "version"], "properties": {"service": {"type": "string", "example": "wirely-api"}, "status": {"type": "string", "example": "ok"}, "version": {"type": "string", "example": "0.9.0"}}},
      "SendOptions": {"type": "object", "required": ["presence", "delay"], "additionalProperties": false, "properties": {"presence": {"type": "string", "enum": ["composing", "recording"], "description": "composing exibe Digitando; recording exibe Gravando áudio."}, "delay": {"type": "integer", "minimum": 0, "maximum": 60000, "description": "Tempo em milissegundos que a presença fica visível antes do envio."}}},
      "TextRequest": {"type": "object", "required": ["recipient", "message"], "additionalProperties": false, "properties": {"recipient": {"type": "string", "description": "Telefone com código do país", "example": "5511999999999"}, "options": {"$ref": "#/components/schemas/SendOptions"}, "message": {"type": "string", "minLength": 1, "maxLength": 4096, "example": "Olá pelo Wirely"}}},
      "LocationRequest": {"type": "object", "required": ["recipient", "latitude", "longitude"], "additionalProperties": false, "properties": {"recipient": {"type": "string", "description": "Telefone com código do país ou JID de grupo", "example": "5511999999999"}, "options": {"$ref": "#/components/schemas/SendOptions"}, "latitude": {"type": "number", "minimum": -90, "maximum": 90, "example": -23.5505}, "longitude": {"type": "number", "minimum": -180, "maximum": 180, "example": -46.6333}, "name": {"type": "string", "maxLength": 200, "example": "Praça da Sé"}, "address": {"type": "string", "maxLength": 500, "example": "Sé, São Paulo - SP"}}},
      "ContactRequest": {"type": "object", "required": ["recipient", "fullName", "phone"], "additionalProperties": false, "properties": {"recipient": {"type": "string", "description": "Telefone com código do país ou JID de grupo", "example": "5511999999999"}, "options": {"$ref": "#/components/schemas/SendOptions"}, "fullName": {"type": "string", "minLength": 1, "maxLength": 200, "example": "Maria Silva"}, "organization": {"type": "string", "maxLength": 200, "example": "Wirely"}, "phone": {"type": "string", "description": "Telefone do contato com código do país", "example": "5511888888888"}}},
      "PollRequest": {"type": "object", "required": ["recipient", "question", "choices"], "additionalProperties": false, "properties": {"recipient": {"type": "string", "description": "Telefone com código do país ou JID de grupo", "example": "5511999999999"}, "options": {"$ref": "#/components/schemas/SendOptions"}, "question": {"type": "string", "minLength": 1, "maxLength": 255, "example": "Qual horário você prefere?"}, "choices": {"type": "array", "minItems": 2, "maxItems": 12, "uniqueItems": true, "items": {"type": "string", "minLength": 1, "maxLength": 100}, "example": ["09:00", "14:00"]}, "maxAnswer": {"type": "integer", "minimum": 1, "default": 1, "description": "Máximo de opções que cada participante pode selecionar."}}},
      "ReactionRequest": {"type": "object", "required": ["recipient", "messageId", "reaction"], "additionalProperties": false, "properties": {"recipient": {"type": "string", "description": "Telefone com código do país ou JID do grupo onde está a mensagem", "example": "5511999999999"}, "options": {"$ref": "#/components/schemas/SendOptions"}, "messageId": {"type": "string", "minLength": 1, "maxLength": 200}, "reaction": {"type": "string", "maxLength": 8, "description": "Emoji da reação. Envie uma string vazia para remover a reação.", "example": "👍"}, "fromMe": {"type": "boolean", "default": false, "description": "Verdadeiro quando a mensagem alvo foi enviada pela própria instância."}, "participant": {"type": "string", "description": "JID ou telefone do autor; obrigatório para mensagem recebida em grupo."}}},
      "DeleteMessageRequest": {"type": "object", "required": ["chat", "messageId"], "additionalProperties": false, "properties": {"chat": {"type": "string", "example": "5511999999999"}, "messageId": {"type": "string", "minLength": 1, "maxLength": 200}, "participant": {"type": "string", "description": "Autor da mensagem quando a exclusão administrativa ocorrer em grupo."}}},
      "EditMessageRequest": {"type": "object", "required": ["chat", "messageId", "message"], "additionalProperties": false, "properties": {"chat": {"type": "string", "example": "5511999999999"}, "messageId": {"type": "string", "minLength": 1, "maxLength": 200}, "message": {"type": "string", "minLength": 1, "maxLength": 4096}}},
      "MarkMessagesReadRequest": {"type": "object", "required": ["chat", "messageIds"], "additionalProperties": false, "properties": {"chat": {"type": "string", "example": "5511999999999"}, "messageIds": {"type": "array", "minItems": 1, "maxItems": 100, "items": {"type": "string", "minLength": 1, "maxLength": 200}}, "participant": {"type": "string", "description": "Obrigatório em grupos; todas as mensagens devem ter o mesmo autor."}}},
      "ChatActionRequest": {"type": "object", "required": ["chat"], "additionalProperties": false, "properties": {"chat": {"type": "string", "example": "5511999999999"}}},
      "ArchiveChatRequest": {"type": "object", "required": ["chat"], "additionalProperties": false, "properties": {"chat": {"type": "string", "example": "5511999999999"}, "archived": {"type": "boolean", "default": true}}},
      "MuteChatRequest": {"type": "object", "required": ["chat"], "additionalProperties": false, "properties": {"chat": {"type": "string", "example": "5511999999999"}, "durationSeconds": {"type": "integer", "minimum": 0, "maximum": 31536000, "default": 0, "description": "Zero silencia sem prazo."}}},
      "MessageActionResult": {"type": "object", "required": ["messageId", "chat", "status"], "properties": {"messageId": {"type": "string"}, "chat": {"type": "string"}, "status": {"type": "string", "enum": ["deleted", "edited", "read"]}}},
      "ChatActionResult": {"type": "object", "required": ["chat", "action", "status"], "properties": {"chat": {"type": "string"}, "action": {"type": "string", "enum": ["archive", "mute", "pin", "unpin"]}, "status": {"type": "string", "enum": ["archived", "unarchived", "muted", "pinned", "unpinned"]}}},
      "MessageStatus": {"type": "object", "required": ["messageId", "status", "updatedAt"], "properties": {"messageId": {"type": "string"}, "status": {"type": "string", "enum": ["sent", "delivered", "read", "read-self", "played", "played-self", "retry", "server-error"]}, "chat": {"type": "string"}, "updatedAt": {"type": "string", "format": "date-time"}}},
      "Newsletter": {"type": "object", "required": ["jid", "name", "subscribers", "state"], "properties": {"jid": {"type": "string"}, "name": {"type": "string"}, "description": {"type": "string"}, "inviteCode": {"type": "string"}, "subscribers": {"type": "integer"}, "state": {"type": "string"}, "role": {"type": "string"}, "mute": {"type": "string"}, "verification": {"type": "string"}}},
      "NewsletterInviteRequest": {"type": "object", "required": ["key"], "additionalProperties": false, "properties": {"key": {"type": "string", "maxLength": 512}}},
      "NewsletterMessagesRequest": {"type": "object", "required": ["jid"], "additionalProperties": false, "properties": {"jid": {"type": "string"}, "count": {"type": "integer", "minimum": 1, "maximum": 100, "default": 20}, "before": {"type": "integer", "minimum": 0}}},
      "LabelEditRequest": {"type": "object", "required": ["name", "color"], "additionalProperties": false, "properties": {"name": {"type": "string", "maxLength": 100}, "color": {"type": "integer", "minimum": 0, "maximum": 255}, "deleted": {"type": "boolean", "default": false}}},
      "CommunityCreateRequest": {"type": "object", "required": ["name"], "additionalProperties": false, "properties": {"name": {"type": "string", "minLength": 1, "maxLength": 25}}},
      "SentMessage": {"type": "object", "required": ["id", "recipient", "timestamp", "type"], "properties": {"id": {"type": "string"}, "recipient": {"type": "string"}, "timestamp": {"type": "string", "format": "date-time"}, "type": {"type": "string", "enum": ["text", "image", "video", "audio", "document", "sticker", "location", "contact", "poll", "reaction"]}}},
      "ReceivedMediaMetadata": {"type": "object", "required": ["available", "type", "mimetype", "fileName", "size", "downloadUrl"], "properties": {"available": {"type": "boolean"}, "type": {"type": "string", "enum": ["image", "video", "audio", "document", "sticker"]}, "mimetype": {"type": "string"}, "fileName": {"type": "string"}, "size": {"type": "integer", "minimum": 0}, "downloadUrl": {"type": "string", "example": "/api/messages/3EB0ABC/media"}, "caption": {"type": "string"}, "duration": {"type": "integer", "minimum": 0}, "voice": {"type": "boolean"}, "animated": {"type": "boolean"}, "savedAt": {"type": "string", "format": "date-time"}, "error": {"type": "string"}}},
      "ReceivedMediaBase64": {"type": "object", "required": ["messageId", "type", "mimetype", "fileName", "size", "data"], "properties": {"messageId": {"type": "string"}, "type": {"type": "string"}, "mimetype": {"type": "string"}, "fileName": {"type": "string"}, "size": {"type": "integer", "minimum": 0}, "data": {"type": "string", "format": "byte"}}},
      "QueueTextRequest": {"type": "object", "required": ["recipient", "message"], "additionalProperties": false, "properties": {"recipient": {"type": "string", "example": "5511999999999"}, "message": {"type": "string", "minLength": 1, "maxLength": 4096}, "scheduledAt": {"type": "string", "format": "date-time", "description": "Opcional; no máximo 365 dias no futuro."}}},
      "JobPayload": {"type": "object", "properties": {"message": {"type": "string"}, "caption": {"type": "string"}, "voice": {"type": "boolean"}, "mimeType": {"type": "string"}, "fileName": {"type": "string"}, "fileSize": {"type": "integer"}}},
      "MessageJob": {"type": "object", "required": ["id", "instanceId", "kind", "recipient", "payload", "status", "attempt", "maxAttempts", "scheduledAt", "createdAt", "updatedAt"], "properties": {"id": {"type": "string"}, "instanceId": {"type": "string"}, "kind": {"type": "string", "enum": ["text", "image", "video", "audio", "document", "sticker"]}, "recipient": {"type": "string"}, "payload": {"$ref": "#/components/schemas/JobPayload"}, "idempotencyKey": {"type": "string"}, "status": {"type": "string", "enum": ["queued", "processing", "retrying", "sent", "failed", "canceled"]}, "attempt": {"type": "integer"}, "maxAttempts": {"type": "integer"}, "scheduledAt": {"type": "string", "format": "date-time"}, "nextAttemptAt": {"type": "string", "format": "date-time"}, "lastError": {"type": "string"}, "result": {"$ref": "#/components/schemas/SentMessage"}, "createdAt": {"type": "string", "format": "date-time"}, "updatedAt": {"type": "string", "format": "date-time"}, "completedAt": {"type": "string", "format": "date-time"}}},
      "Profile": {"type": "object", "required": ["jid", "name"], "properties": {"jid": {"type": "string"}, "name": {"type": "string"}, "about": {"type": "string"}, "pictureId": {"type": "string"}, "pictureUrl": {"type": "string", "format": "uri"}}},
      "UpdateProfileRequest": {"type": "object", "minProperties": 1, "additionalProperties": false, "properties": {"name": {"type": "string", "minLength": 1, "maxLength": 25}, "about": {"type": "string", "maxLength": 139}}},
      "PrivacySettings": {"type": "object", "required": ["groupAdd", "lastSeen", "status", "profile", "readReceipts", "callAdd", "online", "messages", "defense", "stickers"], "properties": {"groupAdd": {"type": "string"}, "lastSeen": {"type": "string"}, "status": {"type": "string"}, "profile": {"type": "string"}, "readReceipts": {"type": "string"}, "callAdd": {"type": "string"}, "online": {"type": "string"}, "messages": {"type": "string"}, "defense": {"type": "string"}, "stickers": {"type": "string"}}},
      "UpdatePrivacyRequest": {"type": "object", "required": ["setting", "value"], "additionalProperties": false, "properties": {"setting": {"type": "string", "enum": ["groupAdd", "lastSeen", "status", "profile", "readReceipts", "online", "callAdd", "messages", "defense", "stickers"]}, "value": {"type": "string", "description": "Valores permitidos dependem da configuração; respostas inválidas retornam 422."}}},
      "GroupParticipant": {"type": "object", "required": ["jid", "isAdmin", "isSuperAdmin"], "properties": {"jid": {"type": "string"}, "phone": {"type": "string"}, "lid": {"type": "string"}, "displayName": {"type": "string"}, "isAdmin": {"type": "boolean"}, "isSuperAdmin": {"type": "boolean"}, "error": {"type": "integer"}}},
      "Group": {"type": "object", "required": ["jid", "name", "isLocked", "isAnnounce", "isCommunity", "joinApprovalRequired", "participantCount", "participants"], "properties": {"jid": {"type": "string"}, "name": {"type": "string"}, "topic": {"type": "string"}, "owner": {"type": "string"}, "createdAt": {"type": "string", "format": "date-time"}, "isLocked": {"type": "boolean"}, "isAnnounce": {"type": "boolean"}, "isCommunity": {"type": "boolean"}, "linkedParentJid": {"type": "string"}, "joinApprovalRequired": {"type": "boolean"}, "participantCount": {"type": "integer"}, "participants": {"type": "array", "items": {"$ref": "#/components/schemas/GroupParticipant"}}}},
      "CreateGroupRequest": {"type": "object", "required": ["name", "participants"], "additionalProperties": false, "properties": {"name": {"type": "string", "minLength": 1, "maxLength": 25}, "participants": {"type": "array", "minItems": 1, "maxItems": 1023, "uniqueItems": true, "items": {"type": "string"}}}},
      "UpdateGroupNameRequest": {"type": "object", "required": ["name"], "additionalProperties": false, "properties": {"name": {"type": "string", "minLength": 1, "maxLength": 25}}},
      "UpdateGroupParticipantsRequest": {"type": "object", "required": ["action", "participants"], "additionalProperties": false, "properties": {"action": {"type": "string", "enum": ["add", "remove", "promote", "demote"]}, "participants": {"type": "array", "minItems": 1, "maxItems": 1023, "uniqueItems": true, "items": {"type": "string"}}}},
      "JoinGroupRequest": {"type": "object", "required": ["code"], "additionalProperties": false, "properties": {"code": {"type": "string", "minLength": 1, "maxLength": 512, "description": "Código ou URL completa de convite."}}},
      "User": {"type": "object", "required": ["id", "username", "role", "enabled"], "properties": {"id": {"type": "string"}, "username": {"type": "string"}, "role": {"type": "string", "enum": ["owner", "admin", "operator", "viewer"]}, "enabled": {"type": "boolean"}, "createdAt": {"type": "string", "format": "date-time"}, "updatedAt": {"type": "string", "format": "date-time"}, "lastLoginAt": {"type": "string", "format": "date-time"}}},
      "CreateUserRequest": {"type": "object", "required": ["username", "password", "role"], "additionalProperties": false, "properties": {"username": {"type": "string", "minLength": 3, "maxLength": 40, "pattern": "^[A-Za-z0-9._-]+$"}, "password": {"type": "string", "minLength": 12, "maxLength": 128, "writeOnly": true}, "role": {"type": "string", "enum": ["admin", "operator", "viewer"]}}},
      "UpdateUserRequest": {"type": "object", "additionalProperties": false, "properties": {"role": {"type": "string", "enum": ["admin", "operator", "viewer"]}, "enabled": {"type": "boolean"}}},
      "ResetUserPasswordRequest": {"type": "object", "required": ["password"], "additionalProperties": false, "properties": {"password": {"type": "string", "minLength": 12, "maxLength": 128, "writeOnly": true}}},
      "LoginRequest": {"type": "object", "required": ["password"], "additionalProperties": false, "properties": {"username": {"type": "string", "default": "admin"}, "password": {"type": "string", "writeOnly": true}}},
      "ChangePasswordRequest": {"type": "object", "required": ["currentPassword", "newPassword"], "additionalProperties": false, "properties": {"currentPassword": {"type": "string", "writeOnly": true}, "newPassword": {"type": "string", "minLength": 12, "maxLength": 128, "writeOnly": true}}},
      "CreateInstanceRequest": {"type": "object", "required": ["name"], "additionalProperties": false, "properties": {"name": {"type": "string", "minLength": 2, "maxLength": 60}}},
      "ChatTextRequest": {"type": "object", "required": ["message"], "additionalProperties": false, "properties": {"message": {"type": "string", "minLength": 1, "maxLength": 4096}}},
      "InstanceList": {"type": "object", "required": ["data"], "properties": {"data": {"type": "array", "items": {"$ref": "#/components/schemas/Instance"}}}},
      "Instance": {"type": "object", "required": ["id", "name", "engine", "status", "createdAt", "updatedAt"], "properties": {"id": {"type": "string"}, "name": {"type": "string"}, "engine": {"type": "string"}, "status": {"type": "string"}, "createdAt": {"type": "string", "format": "date-time"}, "updatedAt": {"type": "string", "format": "date-time"}, "apiToken": {"type": "string", "writeOnly": true}}},
      "ConnectionState": {"type": "object", "required": ["status", "qrAvailable"], "properties": {"status": {"type": "string"}, "qrAvailable": {"type": "boolean"}, "qrExpiresAt": {"type": "string", "format": "date-time"}, "lastError": {"type": "string"}}},
      "PairInstanceRequest": {"type": "object", "required": ["phone"], "additionalProperties": false, "properties": {"phone": {"type": "string", "pattern": "^[1-9][0-9]{7,14}$", "example": "5511999999999"}}},
      "PairInstanceResponse": {"type": "object", "required": ["code", "expiresIn"], "properties": {"code": {"type": "string"}, "expiresIn": {"type": "integer", "example": 160}}},
      "QRCodeBase64": {"type": "object", "required": ["mimetype", "data"], "properties": {"mimetype": {"type": "string", "const": "image/png"}, "data": {"type": "string", "format": "byte"}}},
      "ContactCheckRequest": {"type": "object", "required": ["phones"], "additionalProperties": false, "properties": {"phones": {"type": "array", "minItems": 1, "maxItems": 100, "uniqueItems": true, "items": {"type": "string", "pattern": "^[1-9][0-9]{7,14}$"}, "example": ["5511999999999", "5511888888888"]}}},
      "ContactCheck": {"type": "object", "required": ["phone", "exists"], "properties": {"phone": {"type": "string"}, "jid": {"type": "string"}, "exists": {"type": "boolean"}}},
      "TokenResponse": {"type": "object", "properties": {"token": {"type": "string", "writeOnly": true}, "regenerationRequired": {"type": "boolean"}}},
      "WebhookConfig": {"type": "object", "required": ["url", "enabled", "hasSecret", "events"], "properties": {"url": {"type": "string"}, "enabled": {"type": "boolean"}, "hasSecret": {"type": "boolean"}, "secret": {"type": "string", "writeOnly": true}, "events": {"type": "array", "items": {"type": "string"}}}},
      "WebhookRequest": {"type": "object", "required": ["url"], "additionalProperties": false, "properties": {"url": {"type": "string", "maxLength": 2048}, "enabled": {"type": "boolean"}, "events": {"type": "array", "uniqueItems": true, "items": {"type": "string"}}, "rotateSecret": {"type": "boolean"}}},
      "Contact": {"type": "object", "required": ["jid", "name"], "properties": {"jid": {"type": "string"}, "name": {"type": "string"}, "phone": {"type": "string"}, "firstName": {"type": "string"}, "fullName": {"type": "string"}, "pushName": {"type": "string"}, "businessName": {"type": "string"}}},
      "ChatMessage": {"type": "object", "required": ["eventId", "event", "chat", "fromMe", "isGroup", "timestamp", "data"], "properties": {"eventId": {"type": "string"}, "messageId": {"type": "string"}, "event": {"type": "string"}, "chat": {"type": "string"}, "sender": {"type": "string"}, "fromMe": {"type": "boolean"}, "isGroup": {"type": "boolean"}, "pushName": {"type": "string"}, "type": {"type": "string"}, "text": {"type": "string"}, "timestamp": {"type": "string", "format": "date-time"}, "data": {"type": "object"}}},
      "ChatSummary": {"type": "object", "required": ["chat", "name", "isGroup", "unreadCount", "lastMessage"], "properties": {"chat": {"type": "string"}, "name": {"type": "string"}, "isGroup": {"type": "boolean"}, "unreadCount": {"type": "integer"}, "lastMessage": {"$ref": "#/components/schemas/ChatMessage"}}},
      "ActivityEvent": {"type": "object", "required": ["id", "instanceId", "event", "timestamp", "data"], "properties": {"id": {"type": "string"}, "instanceId": {"type": "string"}, "event": {"type": "string"}, "timestamp": {"type": "string", "format": "date-time"}, "data": {"type": "object"}}},
      "WebhookDelivery": {"type": "object", "required": ["id", "eventId", "instanceId", "event", "url", "attempt", "status", "durationMs", "manual", "createdAt"], "properties": {"id": {"type": "integer"}, "eventId": {"type": "string"}, "instanceId": {"type": "string"}, "event": {"type": "string"}, "url": {"type": "string"}, "attempt": {"type": "integer"}, "status": {"type": "string"}, "httpStatus": {"type": "integer"}, "error": {"type": "string"}, "durationMs": {"type": "integer"}, "manual": {"type": "boolean"}, "createdAt": {"type": "string", "format": "date-time"}}},
      "WebhookAccepted": {"type": "object", "required": ["eventId", "status"], "properties": {"eventId": {"type": "string"}, "status": {"type": "string", "const": "queued"}}},
      "WebhookJob": {"type": "object", "required": ["eventId", "instanceId", "event", "status", "attempt", "maxAttempts", "manual"], "properties": {"eventId": {"type": "string"}, "instanceId": {"type": "string"}, "event": {"type": "string"}, "status": {"type": "string", "enum": ["queued", "processing", "retrying", "delivered", "dead"]}, "attempt": {"type": "integer", "minimum": 0}, "maxAttempts": {"type": "integer", "minimum": 1}, "nextAttemptAt": {"type": "string", "format": "date-time"}, "lastHttpStatus": {"type": "integer"}, "lastError": {"type": "string"}, "manual": {"type": "boolean"}}},
      "AuditEntry": {"type": "object", "required": ["id", "action", "status", "details", "createdAt"], "properties": {"id": {"type": "string"}, "userId": {"type": "string"}, "username": {"type": "string"}, "action": {"type": "string"}, "targetType": {"type": "string"}, "targetId": {"type": "string"}, "status": {"type": "integer"}, "sourceIp": {"type": "string"}, "details": {"type": "object"}, "createdAt": {"type": "string", "format": "date-time"}}},
      "Backup": {"type": "object", "required": ["id", "createdAt", "size", "reason", "version"], "properties": {"id": {"type": "string"}, "createdAt": {"type": "string", "format": "date-time"}, "size": {"type": "integer"}, "reason": {"type": "string", "enum": ["manual", "automatic", "pre-restore"]}, "version": {"type": "integer"}}},
      "BackupStatus": {"type": "object", "required": ["data", "automatic", "intervalHours", "retention"], "properties": {"data": {"type": "array", "items": {"$ref": "#/components/schemas/Backup"}}, "automatic": {"type": "boolean"}, "intervalHours": {"type": "number"}, "retention": {"type": "integer"}, "nextBackupAt": {"type": "string", "format": "date-time"}}},
      "Alert": {"type": "object", "required": ["id", "severity", "title", "message"], "properties": {"id": {"type": "string"}, "severity": {"type": "string", "enum": ["info", "warning", "critical"]}, "title": {"type": "string"}, "message": {"type": "string"}, "instanceId": {"type": "string"}}},
      "AlertList": {"type": "object", "required": ["data", "total", "generatedAt"], "properties": {"data": {"type": "array", "items": {"$ref": "#/components/schemas/Alert"}}, "total": {"type": "integer"}, "generatedAt": {"type": "string", "format": "date-time"}}},
      "AuditPage": {"allOf": [{"$ref": "#/components/schemas/PageMeta"}, {"type": "object", "properties": {"data": {"type": "array", "items": {"$ref": "#/components/schemas/AuditEntry"}}}}]},
      "ActivityPage": {"allOf": [{"$ref": "#/components/schemas/PageMeta"}, {"type": "object", "properties": {"data": {"type": "array", "items": {"$ref": "#/components/schemas/ActivityEvent"}}}}]},
      "WebhookDeliveryPage": {"allOf": [{"$ref": "#/components/schemas/PageMeta"}, {"type": "object", "properties": {"data": {"type": "array", "items": {"$ref": "#/components/schemas/WebhookDelivery"}}}}]},
      "ContactPage": {"allOf": [{"$ref": "#/components/schemas/PageMeta"}, {"type": "object", "properties": {"data": {"type": "array", "items": {"$ref": "#/components/schemas/Contact"}}}}]},
      "ChatPage": {"allOf": [{"$ref": "#/components/schemas/PageMeta"}, {"type": "object", "properties": {"data": {"type": "array", "items": {"$ref": "#/components/schemas/ChatSummary"}}}}]},
      "ChatMessagePage": {"allOf": [{"$ref": "#/components/schemas/PageMeta"}, {"type": "object", "properties": {"data": {"type": "array", "items": {"$ref": "#/components/schemas/ChatMessage"}}}}]},
      "MessageJobPage": {"allOf": [{"$ref": "#/components/schemas/PageMeta"}, {"type": "object", "properties": {"data": {"type": "array", "items": {"$ref": "#/components/schemas/MessageJob"}}}}]},
      "PageMeta": {"type": "object", "required": ["page", "pageSize", "total", "totalPages"], "properties": {"page": {"type": "integer"}, "pageSize": {"type": "integer"}, "total": {"type": "integer"}, "totalPages": {"type": "integer"}}},
      "Error": {"type": "object", "required": ["error"], "properties": {"error": {"type": "string"}}}
    },
    "requestBodies": {
      "NewsletterCreate": {"required": true, "content": {"application/json": {"schema": {"type": "object", "required": ["name"], "additionalProperties": false, "properties": {"name": {"type": "string", "minLength": 1, "maxLength": 100}, "description": {"type": "string", "maxLength": 2048}}}}}},
      "NewsletterJID": {"required": true, "content": {"application/json": {"schema": {"type": "object", "required": ["jid"], "additionalProperties": false, "properties": {"jid": {"type": "string", "pattern": "@newsletter$"}}}}}},
      "ChatLabel": {"required": true, "content": {"application/json": {"schema": {"type": "object", "required": ["chat", "labelId"], "additionalProperties": false, "properties": {"chat": {"type": "string"}, "labelId": {"type": "string"}}}}}},
      "MessageLabel": {"required": true, "content": {"application/json": {"schema": {"type": "object", "required": ["chat", "messageId", "labelId"], "additionalProperties": false, "properties": {"chat": {"type": "string"}, "messageId": {"type": "string"}, "labelId": {"type": "string"}}}}}},
      "CommunityGroups": {"required": true, "content": {"application/json": {"schema": {"type": "object", "required": ["communityJid", "groupJids"], "additionalProperties": false, "properties": {"communityJid": {"type": "string"}, "groupJids": {"type": "array", "minItems": 1, "maxItems": 100, "uniqueItems": true, "items": {"type": "string"}}}}}}},
      "ProfilePhoto": {"required": true, "content": {"multipart/form-data": {"schema": {"type": "object", "required": ["file"], "properties": {"file": {"type": "string", "format": "binary", "description": "JPEG de até 5 MB."}}}}}},
      "Media": {"required": true, "content": {"multipart/form-data": {"schema": {"type": "object", "required": ["recipient", "type", "file"], "properties": {"recipient": {"type": "string", "example": "5511999999999"}, "options": {"$ref": "#/components/schemas/SendOptions"}, "type": {"type": "string", "enum": ["image", "video", "audio", "document", "sticker"]}, "file": {"type": "string", "format": "binary"}, "caption": {"type": "string", "maxLength": 1024, "description": "Imagem, vídeo e documento; figurinha não aceita legenda."}, "voice": {"type": "boolean", "description": "Somente áudio; OGG/Opus obrigatório quando verdadeiro."}}}}}},
      "QueueMedia": {"required": true, "content": {"multipart/form-data": {"schema": {"type": "object", "required": ["recipient", "type", "file"], "properties": {"recipient": {"type": "string", "example": "5511999999999"}, "type": {"type": "string", "enum": ["image", "video", "audio", "document", "sticker"]}, "file": {"type": "string", "format": "binary"}, "caption": {"type": "string", "maxLength": 1024}, "voice": {"type": "boolean"}, "scheduledAt": {"type": "string", "format": "date-time"}}}}}}
    },
    "responses": {
      "Sent": {"description": "Mensagem aceita pelo WhatsApp", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/SentMessage"}}}},
      "Queued": {"description": "Estado do envio assíncrono", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/MessageJob"}}}},
      "Conflict": {"description": "Conflito de idempotência ou estado", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Error"}}}},
      "NotFound": {"description": "Job não encontrado", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Error"}}}},
      "BadRequest": {"description": "Requisição malformada", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Error"}}}},
      "Unauthorized": {"description": "Token inválido ou ausente", "headers": {"WWW-Authenticate": {"schema": {"type": "string"}}}, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Error"}}}},
      "Forbidden": {"description": "Papel autenticado sem permissão para a ação", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Error"}}}},
      "NotConnected": {"description": "Instância desconectada", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Error"}}}},
      "TooLarge": {"description": "Arquivo maior que 32 MB", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Error"}}}},
      "InvalidPayload": {"description": "Conteúdo inválido", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Error"}}}},
      "RateLimited": {"description": "Limite excedido ou login temporariamente bloqueado", "headers": {"Retry-After": {"schema": {"type": "integer"}}}, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Error"}}}}
    }
  }
}`

func openAPI(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.Header().Set("Cache-Control", "public, max-age=300")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte(openAPISpec))
}
